/**
 * mail/manifest.js
 *
 * PILE LAYOUT — all pieces stack in a dense pile near the canvas center.
 * The canvas is now viewport-height (not 3000px tall) because the mail
 * lives inside the drawer, not spread across a scrollable desk.
 *
 * Z-index order = stacking order (higher = on top).
 * Rotations vary: no two identical (verified — every value below is unique),
 * range -14...+16. Use half-degree increments when adding a new piece if
 * the nearest integer is already taken by another entry.
 *
 * The top 10 pieces (by zIndex) are "liftable" — clicking brings them
 * to the very top of the pile. rustle.js handles this.
 */

export const MANIFEST = [

  // ── Bottom of pile ────────────────────────────────────────────────────────

  {
    id:            'postcard-mom-01',
    src:           'mail/postcard-mom-01.html',
    senderId:      'mom',
    postmarkIndex: 0,
    top:           180,
    left:          110,
    zIndex:        2,
    rotation:      -7,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Postcard from Edith Voss, postmarked March 1997',
  },

  {
    id:            'postcard-friend-01',
    src:           'mail/postcard-friend-01.html',
    senderId:      'friend',
    postmarkIndex: 1,
    top:           140,
    left:          160,
    zIndex:        3,
    rotation:      11,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Postcard from Margot Reyes in Tucson, postmarked April 1997',
  },

  {
    id:            'envelope-landlord-01',
    src:           'mail/envelope-landlord-01.html',
    senderId:      'landlord',
    postmarkIndex: 11,
    top:           220,
    left:          90,
    zIndex:        4,
    rotation:      6,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Notice envelope from Dale Pringle (landlord), postmarked June 1998',
  },

  {
    id:            'mailer-video-01',
    src:           'mail/mailer-video-01.html',
    senderId:      'video',
    postmarkIndex: 12,
    top:           200,
    left:          80,
    zIndex:        5,
    rotation:      -4,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'SunCoast Video padded mailer with VHS shipment, postmarked August 1998',
  },

  {
    id:            'letter-ex-01',
    src:           'mail/letter-ex-01.html',
    senderId:      'ex',
    postmarkIndex: 8,
    top:           160,
    left:          130,
    zIndex:        6,
    rotation:      -12,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Personal letter from T. Hargrove, postmarked January 1998',
  },

  {
    id:            'greeting-card-friend-01',
    src:           'mail/greeting-card-friend-01.html',
    senderId:      'friend',
    postmarkIndex: 9,
    top:           190,
    left:          200,
    zIndex:        7,
    rotation:      8,
    speed:         0,
    flip:          'rise',
    ariaLabel:     "Valentine's Day greeting card from Margot Reyes, postmarked February 1998",
  },

  {
    id:            'envelope-dentist-01',
    src:           'mail/envelope-dentist-01.html',
    senderId:      'dentist',
    postmarkIndex: 4,
    top:           150,
    left:          100,
    zIndex:        8,
    rotation:      3,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Appointment reminder envelope from Ashford Family Dental, August 1997',
  },

  // ── Top of pile (liftable) ─────────────────────────────────────────────────

  {
    id:            'postcard-nursery-01',
    src:           'mail/postcard-nursery-01.html',
    senderId:      'nursery',
    postmarkIndex: 2,
    top:           170,
    left:          120,
    zIndex:        9,
    rotation:      -9,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Promotional spring sale postcard from Pacific Garden Nursery, postmarked May 1997',
  },

  {
    id:            'mailer-aol-01',
    src:           'mail/mailer-aol-01.html',
    senderId:      'aol',
    postmarkIndex: 3,
    top:           145,
    left:          145,
    zIndex:        10,
    rotation:      13,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'AOL 100 Hours Free CD-ROM mailer, July 1997',
  },

  {
    id:            'mailer-columbia-01',
    src:           'mail/mailer-columbia-01.html',
    senderId:      'columbia',
    postmarkIndex: 5,
    top:           215,
    left:          95,
    zIndex:        11,
    rotation:      -2,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Columbia House Music Club CD shipment mailer, September 1997',
  },

  {
    id:            'envelope-credit-01',
    src:           'mail/envelope-credit-01.html',
    senderId:      'credit',
    postmarkIndex: 6,
    top:           185,
    left:          175,
    zIndex:        12,
    rotation:      5,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'FirstCard Financial pre-approved credit card offer, October 1997',
  },

  {
    id:            'circular-grocery-01',
    src:           'mail/circular-grocery-01.html',
    senderId:      'grocery',
    postmarkIndex: 7,
    top:           230,
    left:          115,
    zIndex:        13,
    rotation:      -5,
    speed:         0,
    ariaLabel:     'Ashford Market weekly grocery circular, November 1997',
  },

  {
    id:            'summons-court-01',
    src:           'mail/summons-court-01.html',
    senderId:      'court',
    postmarkIndex: 10,
    top:           155,
    left:          155,
    zIndex:        14,
    rotation:      -3,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Jackson County Circuit Court juror summons, March 1998',
  },

  {
    id:            'envelope-charity-01',
    src:           'mail/envelope-charity-01.html',
    senderId:      'charity',
    postmarkIndex: 13,
    top:           205,
    left:          135,
    zIndex:        15,
    rotation:      9,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Oregon Wildlife Alliance charitable solicitation envelope, September 1998',
  },

  {
    id:            'envelope-valpak-01',
    src:           'mail/envelope-valpak-01.html',
    senderId:      'valpak',
    postmarkIndex: 14,
    top:           175,
    left:          100,
    zIndex:        16,
    rotation:      -6,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'ValPak coupon envelope, October 1998',
  },

  {
    id:            'card-wedding-01',
    src:           'mail/card-wedding-01.html',
    senderId:      'wedding',
    postmarkIndex: 15,
    top:           195,
    left:          160,
    zIndex:        17,
    rotation:      4,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Wedding invitation from K. Albright and J. Mora, postmarked December 1998',
  },

  {
    id:            'mailer-campaign-01',
    src:           'mail/mailer-campaign-01.html',
    senderId:      'campaign',
    postmarkIndex: 17,
    top:           165,
    left:          110,
    zIndex:        18,
    rotation:      1,
    speed:         0,
    ariaLabel:     'Citizens for Harlow local political campaign mailer, May 1999',
  },

  // ══════════════════════════════════════════════════════════
  // ADDITIONAL ADAPTED PIECES (33 fragments — postcards, letters,
  // clippings, junk mailers, and desk objects)
  // Positions/zIndex continue on from the pile entries above.
  // Rotations chosen to avoid duplicating any rotation already
  // in use among the first 17 entries.
  // ══════════════════════════════════════════════════════════

  {
    id:            'postcard-scenic-01',
    src:           'mail/postcard-scenic-01.html',
    senderId:      'mom',
    postmarkIndex: 6,
    top:           85,
    left:          70,
    zIndex:        19,
    rotation:      -14,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Scenic postcard from Edith Voss, October 1997',
  },
  {
    id:            'clipping-dispatch-01',
    src:           'mail/clipping-dispatch-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           95,
    left:          85,
    zIndex:        20,
    rotation:      -13,
    speed:         0,
    ariaLabel:     'Newspaper clipping about post office volume',
  },
  {
    id:            'letter-found-01',
    src:           'mail/letter-found-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           105,
    left:          100,
    zIndex:        21,
    rotation:      -11,
    speed:         0,
    ariaLabel:     'Handwritten letter found in a secondhand book',
  },
  {
    id:            'menu-restaurant-01',
    src:           'mail/menu-restaurant-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           115,
    left:          115,
    zIndex:        22,
    rotation:      -10,
    speed:         0,
    ariaLabel:     'Takeout menu on the desk',
  },
  {
    id:            'mailer-clearance-01',
    src:           'mail/mailer-clearance-01.html',
    senderId:      null,
    postmarkIndex: 5,
    top:           125,
    left:          130,
    zIndex:        23,
    rotation:      -8,
    speed:         0,
    ariaLabel:     'Clearance sale mailer from stationery company',
  },
  {
    id:            'postcard-city-01',
    src:           'mail/postcard-city-01.html',
    senderId:      'ex',
    postmarkIndex: 3,
    top:           135,
    left:          145,
    zIndex:        24,
    rotation:      -1,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'City postcard from T. Hargrove, July 1997',
  },
  {
    id:            'clipping-classifieds-01',
    src:           'mail/clipping-classifieds-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           145,
    left:          160,
    zIndex:        25,
    rotation:      2,
    speed:         0,
    ariaLabel:     'Classifieds clipping from local newspaper',
  },
  {
    id:            'mailer-seeds-01',
    src:           'mail/mailer-seeds-01.html',
    senderId:      null,
    postmarkIndex: 2,
    top:           155,
    left:          175,
    zIndex:        26,
    rotation:      5.5,
    speed:         0,
    ariaLabel:     'Seed catalog mailer from Rogue Valley Seed Exchange',
  },
  {
    id:            'envelope-airmail-01',
    src:           'mail/envelope-airmail-01.html',
    senderId:      null,
    postmarkIndex: 6,
    top:           165,
    left:          190,
    zIndex:        27,
    rotation:      7,
    speed:         0,
    flip:          'rise',
    ariaLabel:     'Airmail envelope from overseas sender',
  },
  {
    id:            'photo-polaroid-01',
    src:           'mail/photo-polaroid-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           175,
    left:          205,
    zIndex:        28,
    rotation:      10,
    speed:         0,
    ariaLabel:     'Polaroid photograph on the desk',
  },
  {
    id:            'note-reminders-01',
    src:           'mail/note-reminders-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           185,
    left:          220,
    zIndex:        29,
    rotation:      12,
    speed:         0,
    ariaLabel:     'Handwritten to-do note on the desk',
  },
  {
    id:            'postcard-beach-01',
    src:           'mail/postcard-beach-01.html',
    senderId:      'friend',
    postmarkIndex: 5,
    top:           195,
    left:          235,
    zIndex:        30,
    rotation:      14,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Beach postcard from Margot Reyes, September 1997',
  },
  {
    id:            'note-ps-01',
    src:           'mail/note-ps-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           205,
    left:          80,
    zIndex:        31,
    rotation:      -13.5,
    speed:         0,
    ariaLabel:     'Handwritten sticky note on the desk',
  },
  {
    id:            'postcard-forest-01',
    src:           'mail/postcard-forest-01.html',
    senderId:      'dentist',
    postmarkIndex: 7,
    top:           215,
    left:          110,
    zIndex:        32,
    rotation:      -12.5,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Forest postcard, November 1997',
  },
  {
    id:            'clipping-lifestyle-01',
    src:           'mail/clipping-lifestyle-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           225,
    left:          140,
    zIndex:        33,
    rotation:      -10.5,
    speed:         0,
    ariaLabel:     'Magazine clipping about waiting for the mail',
  },
  {
    id:            'letter-personal-01',
    src:           'mail/letter-personal-01.html',
    senderId:      'video',
    postmarkIndex: 12,
    top:           235,
    left:          170,
    zIndex:        34,
    rotation:      -9.5,
    speed:         0,
    ariaLabel:     'Personal letter from SunCoast Video sender, August 1998',
  },
  {
    id:            'mailer-magazine-01',
    src:           'mail/mailer-magazine-01.html',
    senderId:      null,
    postmarkIndex: 10,
    top:           85,
    left:          70,
    zIndex:        35,
    rotation:      -7.5,
    speed:         0,
    ariaLabel:     'Magazine subscription offer mailer',
  },
  {
    id:            'clipping-recipe-01',
    src:           'mail/clipping-recipe-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           95,
    left:          85,
    zIndex:        36,
    rotation:      -0.5,
    speed:         0,
    ariaLabel:     'Recipe card clipping on the desk',
  },
  {
    id:            'photo-polaroid-02',
    src:           'mail/photo-polaroid-02.html',
    senderId:      null,
    postmarkIndex: null,
    top:           105,
    left:          100,
    zIndex:        37,
    rotation:      2.5,
    speed:         0,
    ariaLabel:     'Second polaroid photograph on the desk',
  },
  {
    id:            'note-about-01',
    src:           'mail/note-about-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           115,
    left:          115,
    zIndex:        38,
    rotation:      4.5,
    speed:         0,
    ariaLabel:     'Personal note about keeping mail',
  },
  {
    id:            'greeting-card-seasonal-01',
    src:           'mail/greeting-card-seasonal-01.html',
    senderId:      'landlord',
    postmarkIndex: 13,
    top:           125,
    left:          130,
    zIndex:        39,
    rotation:      7.5,
    speed:         0,
    flip:          'rotate',
    ariaLabel:     'Seasonal greeting card from Dale Pringle, December 1998',
  },
  {
    id:            'clipping-newsletter-01',
    src:           'mail/clipping-newsletter-01.html',
    senderId:      null,
    postmarkIndex: null,
    top:           135,
    left:          145,
    zIndex:        40,
    rotation:      10.5,
    speed:         0,
    ariaLabel:     'Hobbyist correspondence newsletter clipping',
  },
  {
    id:            'mailer-sweepstakes-01',
    src:           'mail/mailer-sweepstakes-01.html',
    senderId:      null,
    postmarkIndex: 11,
    top:           145,
    left:          160,
    zIndex:        41,
    rotation:      12.5,
    speed:         0,
    ariaLabel:     'Sweepstakes junk mailer',
  },
  {
    id:            'mailer-bookclub-01',
    src:           'mail/mailer-bookclub-01.html',
    senderId:      null,
    postmarkIndex: 10,
    top:           155,
    left:          175,
    zIndex:        42,
    rotation:      14.5,
    speed:         0,
    ariaLabel:     'Quality paperback book club offer mailer',
  },
  {
    id:            'obj-pen',
    src:           'mail/obj-pen.html',
    senderId:      null,
    postmarkIndex: null,
    top:           165,
    left:          190,
    zIndex:        43,
    rotation:      -11.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Pen on the desk',
  },
  {
    id:            'obj-letter-opener',
    src:           'mail/obj-letter-opener.html',
    senderId:      null,
    postmarkIndex: null,
    top:           175,
    left:          205,
    zIndex:        44,
    rotation:      -8.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Letter opener on the desk',
  },
  {
    id:            'obj-wax-seal',
    src:           'mail/obj-wax-seal.html',
    senderId:      null,
    postmarkIndex: null,
    top:           185,
    left:          220,
    zIndex:        45,
    rotation:      -6.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Wax seal on the desk',
  },
  {
    id:            'obj-stamp-strip',
    src:           'mail/obj-stamp-strip.html',
    senderId:      null,
    postmarkIndex: null,
    top:           195,
    left:          235,
    zIndex:        46,
    rotation:      -5.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Strip of stamps on the desk',
  },
  {
    id:            'obj-stamp-eagle',
    src:           'mail/obj-stamp-eagle.html',
    senderId:      null,
    postmarkIndex: null,
    top:           205,
    left:          80,
    zIndex:        47,
    rotation:      -4.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Large eagle stamp on the desk',
  },
  {
    id:            'obj-postmark-deco',
    src:           'mail/obj-postmark-deco.html',
    senderId:      null,
    postmarkIndex: null,
    top:           215,
    left:          110,
    zIndex:        48,
    rotation:      -1.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Decorative postmark graphic',
  },
  {
    id:            'obj-pencil',
    src:           'mail/obj-pencil.html',
    senderId:      null,
    postmarkIndex: null,
    top:           225,
    left:          140,
    zIndex:        49,
    rotation:      1.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Pencil on the desk',
  },
  {
    id:            'obj-airmail-label',
    src:           'mail/obj-airmail-label.html',
    senderId:      null,
    postmarkIndex: null,
    top:           235,
    left:          170,
    zIndex:        50,
    rotation:      6.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Par Avion airmail label',
  },
  {
    id:            'obj-return-labels',
    src:           'mail/obj-return-labels.html',
    senderId:      null,
    postmarkIndex: null,
    top:           85,
    left:          70,
    zIndex:        51,
    rotation:      8.5,
    speed:         0,
    decorative:    true,  // small SVG desk prop, not paper — see CSS note on .is-decorative-object
    ariaLabel:     'Sheet of return address labels',
  },

];
